-- Active: 1731477436449@@127.0.0.1@3306@schoolmanagement
CREATE TABLE `users`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `firstname` VARCHAR(50) NOT NULL,
    `lastname` VARCHAR(50) NOT NULL,
    `email` VARCHAR(50) NOT NULL UNIQUE,
    `phone` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE `students`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT(20) UNSIGNED NOT NULL,
    `roll_number` INT UNIQUE NOT NULL,
    `dob` DATE NOT NULL,
    `phone` VARCHAR(50) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `gurdian_name` VARCHAR(50) NOT NULL,
    `gurdian_phone` VARCHAR(50) NOT NULL,
    `addmission_date` DATE NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
    )


CREATE TABLE `teachers`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT(20) UNSIGNED NOT NULL,
    `subject` VARCHAR(255) NOT NULL,
    `dob` DATE NOT NULL,
    `hire_date` DATE NOT NULL,
    `qualification` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(50) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
    )


CREATE TABLE `parents`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT(20) UNSIGNED NOT NULL,
    `student_id` BIGINT(20) UNSIGNED NOT NULL,
    `relationship` ENUM('Father', 'Mother', 'Guardian') NOT NULL DEFAULT "Father",
    `phone` VARCHAR(50) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE `classes`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `description` TEXT,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE `subjects`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE `student_classs`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `student_id` BIGINT(20) UNSIGNED NOT NULL,
    `class_id` BIGINT(20) UNSIGNED NOT NULL,
    `enrollment_date` DATE NOT NULL,
    `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`class_id`) REFERENCES `classes`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE `teachers_subjects`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `teacher_id` BIGINT(20) UNSIGNED NOT NULL,
    `subject_id` BIGINT(20) UNSIGNED NOT NULL,
    `assign_date` DATE NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`teacher_id`) REFERENCES `teachers`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`subject_id`) REFERENCES `subjects`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE `exams`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `class_id` BIGINT(20) UNSIGNED NOT NULL,
    `subject_id` BIGINT(20) UNSIGNED NOT NULL,
    `exam_date` DATE NOT NULL,
    `exam_type` ENUM('midterm', 'final' , 'quiz' , 'monthly') NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`class_id`) REFERENCES `classes`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`subject_id`) REFERENCES `subjects`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE `student_exams`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `student_id` BIGINT(20) UNSIGNED NOT NULL,
    `exam_id` BIGINT(20) UNSIGNED NOT NULL,
    `marks` INT NOT NULL,
    `status` ENUM('pending','pass', 'fail','absent') NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`exam_id`) REFERENCES `exams`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE `timetable`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `class_id` BIGINT(20) UNSIGNED NOT NULL,
    `subject_id` BIGINT(20) UNSIGNED NOT NULL,
    `teacher_id` BIGINT(20) UNSIGNED NOT NULL,
    `day` ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday') NOT NULL,
    `start_time` TIME NOT NULL,
    `end_time` TIME NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`class_id`) REFERENCES `classes`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`subject_id`) REFERENCES `subjects`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`teacher_id`) REFERENCES `teachers`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE `assignments`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `teacher_id` BIGINT(20) UNSIGNED NOT NULL,
    `class_id` BIGINT(20) UNSIGNED NOT NULL,
    `subject_id` BIGINT(20) UNSIGNED NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `due_date` DATE NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`teacher_id`) REFERENCES `teachers`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`class_id`) REFERENCES `classes`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`subject_id`) REFERENCES `subjects`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE `assignment_submissions`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `student_id` BIGINT(20) UNSIGNED NOT NULL,
    `assignment_id` BIGINT(20) UNSIGNED NOT NULL,
    `submission_date` DATE NOT NULL,
    `grade` INT,
    `file` VARCHAR(255),
    `status` ENUM('late', 'submitted', 'graded') NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`assignment_id`) REFERENCES `assignments`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE `fees`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `student_id` BIGINT(20) UNSIGNED NOT NULL,
    `amount` DECIMAL(10, 2) NOT NULL,
    `porpose` ENUM('monthly_fee', 'fine', 'exam_fee', 'other') NOT NULL,
    `payment_date` DATE NOT NULL,
    `payment_method` ENUM('cash', 'card', 'bank_transfer') NOT NULL,
    `status` ENUM('paid', 'unpaid') NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE `notifications`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT(20) UNSIGNED NOT NULL,
    `massage` VARCHAR(255) NOT NULL,
    `status` ENUM('sent','read', 'unread') NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE `attendance`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `student_id` BIGINT(20) UNSIGNED NOT NULL,
    `class_id` BIGINT(20) UNSIGNED NOT NULL,
    `date` DATE NOT NULL,
    `status` ENUM('present', 'absent', 'late') NOT NULL,
    `remarks` VARCHAR(255),
    FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`class_id`) REFERENCES `classes`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
)

